name: Build and Publish My GitBook

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      MY_SECRET   : ${{secrets.GH_ACCESS_TOKEN}}

    steps:
      - name: Setup Node.js
        run: | 
          sudo apt-get install nodejs
          sudo apt-get install npm
          sudo npm install n -g
          sudo n stable
          npm i -g npm
      - name: Setup gitbook
        run: | 
          npm install -g gitbook-cli
      - name: Checkout main source
        uses: actions/checkout@v2
      - name: Build the book
        working-directory: ${{ github.workspace }}
        run: |
          gitbook install && gitbook build
