name: Build and Publish My GitBook

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-16.04
    env:
      MY_SECRET   : ${{secrets.GH_ACCESS_TOKEN}}

    steps:
      - name: Setup Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: "10.21"
      - name: Setup gitbook
        run: | 
          npm install -g gitbook-cli
      - name: Checkout main source
        uses: actions/checkout@v2
      - name: Build the book
        working-directory: ${{ github.workspace }}
        run: |
          gitbook init && gitbook install && gitbook build
