name: Build and Publish My GitBook

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      MY_SECRET   : ${{secrets.GH_ACCESS_TOKEN}}
      USER_NAME   : <Your Git username>
      USER_EMAIL  : <Your Git email>
      BOOK_DIR    : m2m

    steps:
    - name: test
      run: |
        touch tst
        cp tst tst-$GITHUB_RUN_ID
        ls tst*
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1
